### ISSUE TITLE
#imzML MALDI dataset

### ISSUE THREAD

**Issue by zhangmin-cloud** [hanghu1024/RAW-MSI-generator#2]
cI have the following two questions that I would like to ask you.
1. Regarding the imzML format data downloaded from public datasets, can I use your method?
2. Can I process the .d file output from the MALDI-TOF instrument according to the "example for QTOF" method?
I look forward to your comments.

**Comment by hanghu1024** [comment]
This method currently only supports Thermo .raw and Agilent .d files. And some data process it does is designed for DESI or nano-DESI experiments, where you acquire imaging data line by line. For example, for imzML data or MALDI data, you may not need pixel alignment. But some Python codes here may still be helpful. In case you don't know, there's a Python parser for imzML format: https://github.com/alexandrovteam/pyimzML And a Bruker data API: https://github.com/BlaisProteomics/multiplierz
